### ISSUE TITLE
Doesn't work on devices under 2.3

### ISSUE THREAD

**Issue by ismaeltoe** [flavienlaurent/datetimepicker#41]
03-30 04:02:29.951: E/AndroidRuntime(408): FATAL EXCEPTION: main
03-30 04:02:29.951: E/AndroidRuntime(408): java.lang.NoSuchMethodError: java.util.Calendar.getDisplayName
03-30 04:02:29.951: E/AndroidRuntime(408):  at com.fourmob.datetimepicker.date.DatePickerDialog.updateDisplay(DatePickerDialog.java:167)
03-30 04:02:29.951: E/AndroidRuntime(408):  at com.fourmob.datetimepicker.date.DatePickerDialog.onCreateView(DatePickerDialog.java:301)
03-30 04:02:29.951: E/AndroidRuntime(408):  at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
03-30 04:02:29.951: E/AndroidRuntime(408):  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
03-30 04:02:29.951: E/AndroidRuntime(408):  at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
03-30 04:02:29.951: E/AndroidRuntime(408):  at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
03-30 04:02:29.951: E/AndroidRuntime(408):  at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
03-30 04:02:29.951: E/AndroidRuntime(408):  at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:440)
03-30 04:02:29.951: E/AndroidRuntime(408):  at android.os.Handler.handleCallback(Handler.java:587)
03-30 04:02:29.951: E/AndroidRuntime(408):  at android.os.Handler.dispatchMessage(Handler.java:92)
03-30 04:02:29.951: E/AndroidRuntime(408):  at android.os.Looper.loop(Looper.java:123)
03-30 04:02:29.951: E/AndroidRuntime(408):  at android.app.ActivityThread.main(ActivityThread.java:4627)
03-30 04:02:29.951: E/AndroidRuntime(408):  at java.lang.reflect.Method.invokeNative(Native Method)
03-30 04:02:29.951: E/AndroidRuntime(408):  at java.lang.reflect.Method.invoke(Method.java:521)
03-30 04:02:29.951: E/AndroidRuntime(408):  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:868)
03-30 04:02:29.951: E/AndroidRuntime(408):  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:626)
03-30 04:02:29.951: E/AndroidRuntime(408):  at dalvik.system.NativeStart.main(Native Method)

**Comment by flavienlaurent** [comment]
949b84859966c6aba110fe0fc8731aeab3036dc4

some regression... thanks!

**Comment by ismaeltoe** [comment]
I don't understand. Did you fix the issue? or you decide to not support 2.2
and older versions?

2014-04-01 13:11 GMT+00:00 Flavien Laurent notifications@github.com:

**Comment by flavienlaurent** [comment]
It's fixed
